// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMEG_hklKZ8WKP-qSuTnLpvxy-A9gSqKQ',
    appId: '1:215144997717:web:6fa091ca3a55b4280b85dc',
    messagingSenderId: '215144997717',
    projectId: 'instagram-clone-a502c',
    authDomain: 'instagram-clone-a502c.firebaseapp.com',
    storageBucket: 'instagram-clone-a502c.appspot.com',
    measurementId: 'G-GE3TB96TC9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_mQQvpPwijmyAy-O6M3pfkiW507XVd5Q',
    appId: '1:215144997717:android:6ede0fbd5dd5fdce0b85dc',
    messagingSenderId: '215144997717',
    projectId: 'instagram-clone-a502c',
    storageBucket: 'instagram-clone-a502c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb8mIqI_dsXoCTyl2r1YrtBPBw2oZUYfI',
    appId: '1:215144997717:ios:64b2f4fa388ff8550b85dc',
    messagingSenderId: '215144997717',
    projectId: 'instagram-clone-a502c',
    storageBucket: 'instagram-clone-a502c.appspot.com',
    iosClientId: '215144997717-0fk6pr9mj31u74iui1f61fmo7aa90ddg.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramCloneFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb8mIqI_dsXoCTyl2r1YrtBPBw2oZUYfI',
    appId: '1:215144997717:ios:64b2f4fa388ff8550b85dc',
    messagingSenderId: '215144997717',
    projectId: 'instagram-clone-a502c',
    storageBucket: 'instagram-clone-a502c.appspot.com',
    iosClientId: '215144997717-0fk6pr9mj31u74iui1f61fmo7aa90ddg.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramCloneFlutter',
  );
}
